[build]
  publish = "."

[[edge_functions]]
  path = "/blog-detail"
  function = "seo"

[[edge_functions]]
  path = "/blog-detail.html"
  function = "seo"


[[edge_functions]]
  path = "/portfolio-detail"
  function = "seo"

[[edge_functions]]
  path = "/portfolio-detail.html"
  function = "seo"
